/**
 * Application Route Constants
 *
 * Centralized route definitions for type-safe navigation across the app.
 * Use these constants instead of hardcoded strings in NuxtLink and useRouter().
 */

/**
 * Route names generated by Nuxt based on file structure
 */
export const ROUTE_NAMES = {
  HOME: 'index',
  LOGIN: 'login',
  CONTACT: 'contact',

  // Exercises
  EXERCISES: 'exercises',
  EXERCISE_DETAIL: 'exercises-id',

  // Workouts
  WORKOUTS: 'workouts',
  WORKOUT_DETAIL: 'workouts-id',
  WORKOUT_ADD: 'workouts-id-add',
  WORKOUT_LOG: 'workouts-id-log-exerciseId',

  // Progress
  PROGRESS: 'progress',
  PROGRESS_EXERCISE: 'progress-exerciseId',
} as const;

/**
 * Route paths for direct path-based navigation
 */
export const ROUTE_PATHS = {
  HOME: '/',
  LOGIN: '/login',
  CONTACT: '/contact',

  // Exercises
  EXERCISES: '/exercises',
  exerciseDetail: (id: string) => `/exercises/${id}`,

  // Workouts
  WORKOUTS: '/workouts',
  workoutDetail: (id: string) => `/workouts/${id}`,
  workoutAdd: (id: string) => `/workouts/${id}/add`,
  workoutLog: (sessionId: string, exerciseId: string) =>
    `/workouts/${sessionId}/log/${exerciseId}`,

  // Progress
  PROGRESS: '/progress',
  progressExercise: (exerciseId: string) => `/progress/${exerciseId}`
} as const;

/**
 * Navigation menu items
 */
export interface NavItem {
  name: string;
  path: string;
  routeName: string;
  icon?: string;
}

export const NAV_ITEMS: NavItem[] = [
  {
    name: 'Exercises',
    path: ROUTE_PATHS.EXERCISES,
    routeName: ROUTE_NAMES.EXERCISES,
  },
  {
    name: 'Workouts',
    path: ROUTE_PATHS.WORKOUTS,
    routeName: ROUTE_NAMES.WORKOUTS,
  },
  {
    name: 'Progress',
    path: ROUTE_PATHS.PROGRESS,
    routeName: ROUTE_NAMES.PROGRESS,
  },
];

/**
 * Helper type for route parameters
 */
export interface RouteParams {
  exerciseId?: string;
  sessionId?: string;
  workoutId?: string;
}

/**
 * Type-safe route builder
 */
export const buildRoute = {
  exerciseDetail: (id: string) => ({
    name: ROUTE_NAMES.EXERCISE_DETAIL,
    params: { id },
  }),

  workoutDetail: (id: string) => ({
    name: ROUTE_NAMES.WORKOUT_DETAIL,
    params: { id },
  }),

  workoutAdd: (id: string) => ({
    name: ROUTE_NAMES.WORKOUT_ADD,
    params: { id },
  }),

  workoutLog: (sessionId: string, exerciseId: string) => ({
    name: ROUTE_NAMES.WORKOUT_LOG,
    params: { id: sessionId, exerciseId },
  }),

  progressExercise: (exerciseId: string) => ({
    name: ROUTE_NAMES.PROGRESS_EXERCISE,
    params: { exerciseId },
  })
} as const;
